version: "3.3"

networks:
  pdc:
    driver: overlay

services:

  traefik:
    image: "traefik:v2.2"
    hostname: traefik
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - pdc

  authorizator:
   image: "pdc/authorizator"
   hostname: authorizator
   volumes:
    - ./authorizator:/authorizator
    - ./pdc_dev/pdc:/usr/local/lib/python3.9/site-packages/pdc
   labels:
     - "traefik.enable=true"
     - "traefik.http.routers.authorizator.rule=PathPrefix(`/authorizator`)"
     - "traefik.http.routers.authorizator.entrypoints=web"
     - "traefik.http.services.authorizator.loadbalancer.server.port=80"
     - "traefik.http.middlewares.authorizator.stripprefix.prefixes=/authorizator"
     - "traefik.http.routers.authorizator.middlewares=authorizator"
   networks:
     - pdc
     
  mariadb:
   image: mariadb
   hostname: mariadb
   volumes:
    - ./db:/var/lib/mysql
   environment:
    MYSQL_ROOT_PASSWORD: pdc_dev
   networks:
     - pdc
     
# for visually manage db

  adminer:
   image: adminer
   ports:
    - 8081:8080
   networks:
     - pdc
